### ISSUE TITLE
error after indexing (?)

### ISSUE THREAD

**Issue by ebioman** [samarthrvittal/lookatgraphs#25]
Hello 
I encountered a problem and have trouble to understand the source of it.
I started your program with the following command

```
  ../../Falcon2Fastg/Falcon2Fastg.py --only-output contigs 2> log
```

And it crashes with the following message:

<pre><code>
Traceback (most recent call last):
  File "../../Falcon2Fastg/Falcon2Fastg.py", line 469, in <module>
    make_fastg("contig")
  File "../../Falcon2Fastg/Falcon2Fastg.py", line 270, in make_fastg
    print idx[corrected_name][:]
  File "/software/lib/python2.7/site-packages/pyfaidx/__init__.py", line 676, in __getitem__
    raise KeyError("{0} not in {1}.".format(rname, self.filename))
KeyError: '7450 not in p_ctg.fa.'
</code></pre>

So my guess is that it expects in my primary contigs a sequence named "7450" which does indeed not exists. But where does he get the name actually from ?
Looking into the tilling path, I cant find any "7450" neither.
Thanks

**Comment by rchikhi** [comment]
Hi, how large is your p_contigs.fasta file? Would it be possible to send it by email to us? Rayan.chikhi@univ-lille1.fr 
Thanks.

**Comment by ebioman** [comment]
Hi
Thanks for the answer. Unfortunately I am not free to share this particular one.
But concept wise it should be there, no?
I will investigate further. Any particular ideas otherwise?

**Comment by rchikhi** [comment]
Indeed. Could please you do a grep for 7450 to see where this identifier appears?

**Comment by danshu** [comment]
Hi,

I have the same error when running Falcon2Fastg. I found that the identifier appears in "ctg_paths", and such number-only identifiers seem to be "ctg_circular". 

Best,
Quan

**Comment by wyim-pgl** [comment]
Same here,

genome size is 900Mbp

 egrep 8906 p_ctg.fa
>001500F 000820252:E~002517331:E~000846770:B~000473759:B ctg_linear 138906 458006
>002369F 000748164:B~002418554:B~002113143:B~000536475:E ctg_linear 89069 198250
>004397F 000510770:B~002486943:B~000076530:B~000076530:B ctg_linear 28906 45389
>006726F 002633455:B~000228728:E~000228728:E~000228728:E ctg_linear 8906 2632
>006751F 001904754:E~000890639:E~002055062:B~002055062:B ctg_linear 8770 24591
>007803F 000320971:B~002473608:E~000189061:E~000189061:E ctg_linear 4377 14756
>008549F 000382076:E~000382076:E~001248156:E~001248156:E ctg_linear 1557 8906
